const arr2=[
    {
        id:6,
        name:'Bhumika Nagrecha',
        position:'SD Intern at Bank of New York Mellon',
        description1:'I started my interview preparation journey from the first seminar of O(1). Things were explained very well in detail, from tips and tricks for interviews to resources for DSA and c',
        description2:'nd in contest streaks which improved my coding skills due to which I could clear the off-campus coding test for a job opportunity at Bank Of New York in my 3rd year itself . So in a nutshell, O(1) club is a single point solution for complete placement guidance.',
        linkedin:'https://www.linkedin.com/in/bhumikanagrecha/',
        image:'images/Bhumika Nagrecha.png',
    },
    {
        id:7,
        name:'Sakshi Thakur',
        position:'R&D Intern at VMware',
        description1:'I have been helped a lot from O(1) club! Right from the first seminar, we have been guided in almost everything related to placements. I started participating rigorously in CPL a',
        description2:'ore subjects. As a fresher guidance and resources helped me to learn and grow.',
        linkedin:'https://www.linkedin.com/in/sakshithakur1612',
        image:'images/Sakshi Thakur.png',
    },
    {
        id:8,
        name:'Shrey Agrawal',
        position:'Power Programmer at Infosys',
        description:'My first experience with O(1) coding club was from their first seminar and since then, I have nothing but good things to say. From their guidance relating to placements, both on and off campus,',
        description2:'to their CPL, everything important was explained and helped in becoming better programmers. I was fortunate enough lead a team in CPL, and watching me, my classmates, and juniors improve every contest was a great experience.',
        linkedin:'https://www.linkedin.com/in/shrey-agrawal-329829172/',
        image:'images/Shrey Agrawal.png',
    },
    {
        id:9,
        name:'Yavar Vazir',
        position:'R&D intern at VMware',
        description:'My preparation for Placements started with CPL organised by O(1) Coding Club.It was the best learning experience for me because it had coding problems of all levels, starting right f',
        description2:'rom basics and going up to difficult problems to be solved in 2.5 - 3 hours. It made a good habit of solving problems on daily basis and helped us to have a grip on competitive coding questions. As far as the interviews are concerned, the videos uploaded by O(1) were very helpful particular to each company, where they told us what exactly do they expect and how to prepare for it. I would recommend to anyone who is looking for mentorship, guidance about placements, go for O(1).',
        linkedin:'http://linkedin.com/in/yavar-vazir-a0843a182',
        image:'images/Yavar Vazir.png',
    },
    {
        id:10,
        name:'Rajat Bhanarkar',
        position:'Data Engineer Intern at Amazon',
        description:'I attended the React.js workshop by O(1) Coding Club in Jan. It was a really informative, interactive and organized workshop.Everything was developed from scratch with proper stepwise explanation',
        description2:'.I would highly recommend O(1) Workshops.',
        linkedin:'https://www.linkedin.com/in/rajat-bhanarkar-11a859176',
        image:'images/Rajat Bhanarkar.png',
    },
    {
        id:11,
        name:'Nidhi Sharma',
        position:'SD Intern at Bank of New York Mellon',
        description:'O(1) has guided us, gave us great tips for making resume and ways to crack off-campus opportunities',
        description2:'',
        linkedin:'https://www.linkedin.com/in/nidhivsharma10',
        image:'images/Nidhi Sharma.png',
    },
]
export default arr2;